# This file represents all site settings which are used/processed in ext:theme
themeBase:
  addonSolr:
    search:
      targetPage:
    indexQueue:
      pages:
        indexer:
          authorization:
            username: '%env(SOLR_BASICAUTH_USERNAME)'
            password: '%env(SOLR_BASICAUTH_PASSWORD)'
